[project]
name = "pytorch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "veerpast", email = "131589298+veerpast@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.6.3",
    "numpy>=2.5.3",
    "scikit-learn>=1.9.0",
    "torch>=2.14.0",
]

[project.scripts]
pytorch = "pytorch:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
